sudo: required
services:
   - docker

before_install:
   - docker build -t dockkuberockstar1229/docker-react -f Dockerfile.dev .
   - gem install cocoapods -v '0.32.1'
script:
   - docker run dockkuberockstar1229/docker-react npm run test -- --coverage
deploy:
   provider: elasticbeanstalk

   