sudo: required
services:
   - docker

before_install:
   - docker build -t dockkuberockstar1229/docker-react -f Dockerfile.dev .
script:
   - docker run dockkuberockstar1229/docker-react npm run test -- --coverage
deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "Prabhudocker"
   env: "Prabhudocker-env"
   bucket_name: "elasticbeanstalk-us-east-2-003196989676"
   bucket_path: "Prabhudocker"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
      secure: "$AWS_SECRET_KEY"