sudo: required
services:
   - docker

before_install:
   - docker build -t dockkuberockstar1229/docker-react -f Dockerfile.dev .
   - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de
script:
   - docker run dockkuberockstar1229/docker-react npm run test -- --coverage


   